### PR TITLE
Add onShouldQuit

### LINKED ISSUE #4: Implement uiOnShouldQuit method
This is needed by quit menu items

### PR DESCRIPTION
**Pull request by mischnic**
The code is mostly copied from `UiWindow::onClosing`.
I have no idea if this is the correct way to implement it, but now the "Quit" menu and Cmd+Q works on macOS (not tested on other platforms).
I didn't add anything about the new function to the documentation (not sure if the node callback is correct). You can try it out with `control-gallery.js` and `node-pad.js`.

Fixes #4

### CODE REVIEW

**Comment by mischnic** [comment]
Now that I think about it, `onClosing` is a callback for a specific window, while `onShouldQuit` is for the *whole* application. But my changes add it to the UiWindow, so I guess it should rather be in here:
https://github.com/parro-it/libui-node/blob/4ab86489c80dbfc5ac90d720771c4f27fe6c7fd0/src/Ui.cc#L5-L10

This difference should also be mentioned in the docs.

**Comment by parro-it** [comment]
> onClosing is a callback for a specific window, while onShouldQuit is for the whole application

Yes, I agree with you, the Ui class is the right place to add the new method.

**Comment by mischnic** [comment]
I updated the code.

I guess this should be documented in `initialization.md`?

**Comment by mischnic** [comment]
Build is failing on macOS because of
`No output has been received in the last 10m0s, this potentially indicates a stalled build or something wrong with the build itself.`
Also happens on my mac.

Works when commenting out (`libui.startLoop()` doesn't return/blocks)
```js
test.before(() => {
	libui.startLoop();
});

test.after(() => {
	libui.stopLoop();
});
```

**Comment by parro-it** [comment]
Seems to work well on mac

**Pull request merged**
